name: Deploy To EC2

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Reset GitHub Actions Cache
        run: sudo rm -rf /usr/local/actions/cache || true

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: application-jelly.properties 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-jelly.properties

      - name: Gradle 빌드
        run: ./gradlew clean

      # EC2 #1에 파일 전송 및 배포
      - name: EC2 #1에 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_1_HOST }}
          username: ${{ secrets.EC2_1_USERNAME }}
          key: ${{ secrets.EC2_1_PRIVATE_KEY }}
          source: ./
          target: /home/ubuntu/Salary_BE/tobe

      - name: EC2 #1에 배포 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_1_HOST }}
          username: ${{ secrets.EC2_1_USERNAME }}
          key: ${{ secrets.EC2_1_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/Salary_BE/current
            mkdir /home/ubuntu/Salary_BE/current
            cp -r /home/ubuntu/Salary_BE/tobe/* /home/ubuntu/Salary_BE/current/
            cd /home/ubuntu/Salary_BE/current
            sudo fuser -k -n tcp 8080 || true
            nohup ./gradlew runWebApp > webapp.log 2>&1 &
            rm -rf /home/ubuntu/Salary_BE/tobe

      # EC2 #2에 파일 전송 및 배포
      - name: EC2 #2에 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_2_HOST }}
          username: ${{ secrets.EC2_2_USERNAME }}
          key: ${{ secrets.EC2_2_PRIVATE_KEY }}
          source: ./
          target: /home/ubuntu/Salary_BE/tobe

      - name: EC2 #2에 배포 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_2_HOST }}
          username: ${{ secrets.EC2_2_USERNAME }}
          key: ${{ secrets.EC2_2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/Salary_BE/current
            mkdir /home/ubuntu/Salary_BE/current
            cp -r /home/ubuntu/Salary_BE/tobe/* /home/ubuntu/Salary_BE/current/
            cd /home/ubuntu/Salary_BE/current
            sudo fuser -k -n tcp 8080 || true
            nohup ./gradlew runWebApp > webapp.log 2>&1 &
            rm -rf /home/ubuntu/Salary_BE/tobe
