name: Deploy To EC2

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: application-jelly.properties 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-jelly.properties

      - name: Gradle 빌드 (WebApp & WebServer)
        run: |
          ./gradlew clean bootJarWebApp &
          ./gradlew clean bootJarWebServer &
          wait

      - name: WebApp 빌드 파일 이름 변경
        run: mv ./build/libs/*WebApp*.jar ./webapp.jar

      - name: WebServer 빌드 파일 이름 변경
        run: mv ./build/libs/*WebServer*.jar ./webserver.jar

      # WebApp 배포 (EC2 #1)
      - name: EC2 WebApp에 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_WEBAPP_HOST }}
          username: ${{ secrets.EC2_WEBAPP_USERNAME }}
          key: ${{ secrets.EC2_WEBAPP_PRIVATE_KEY }}
          source: webapp.jar
          target: /home/ubuntu/Salary_BE/tobe

      - name: EC2 WebApp 배포 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_WEBAPP_HOST }}
          username: ${{ secrets.EC2_WEBAPP_USERNAME }}
          key: ${{ secrets.EC2_WEBAPP_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/Salary_BE/current/webapp
            mkdir -p /home/ubuntu/Salary_BE/current/webapp
            mv /home/ubuntu/Salary_BE/tobe/webapp.jar /home/ubuntu/Salary_BE/current/webapp/webapp.jar
            cd /home/ubuntu/Salary_BE/current/webapp
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar webapp.jar > ./webapp.log 2>&1 &

      # WebServer 배포 (EC2 #2)
      - name: EC2 WebServer에 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_WEBSERVER_HOST }}
          username: ${{ secrets.EC2_WEBSERVER_USERNAME }}
          key: ${{ secrets.EC2_WEBSERVER_PRIVATE_KEY }}
          source: webserver.jar
          target: /home/ubuntu/Salary_BE/tobe

      - name: EC2 WebServer 배포 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_WEBSERVER_HOST }}
          username: ${{ secrets.EC2_WEBSERVER_USERNAME }}
          key: ${{ secrets.EC2_WEBSERVER_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/Salary_BE/current/webserver
            mkdir -p /home/ubuntu/Salary_BE/current/webserver
            mv /home/ubuntu/Salary_BE/tobe/webserver.jar /home/ubuntu/Salary_BE/current/webserver/webserver.jar
            cd /home/ubuntu/Salary_BE/current/webserver
            sudo fuser -k -n tcp 8081 || true
            nohup java -jar webserver.jar > ./webserver.log 2>&1 &
