name: Deploy To EC2

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      # GitHub 저장소에서 파일 불러오기
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      # JDK 17 설치
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # application-jelly.properties 파일 생성
      - name: application-jelly.properties 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-jelly.properties

      # Gradle 빌드 (WebApp 및 WebServer)
      - name: Gradle 빌드 (WebApp & WebServer)
        run: |
          ./gradlew jarWebApp
          ./gradlew jarWebServer

      # 빌드 파일 검증 및 확인
      - name: 빌드 파일 확인
        run: |
          echo "WebApp 빌드 파일:"
          ls -l ./build/libs/webapp/
          echo "WebServer 빌드 파일:"
          ls -l ./build/libs/webserver/

      # WebApp 빌드 파일 이름 변경
      - name: WebApp 빌드 파일 이름 변경
        run: |
          WEBAPP_FILE=$(ls ./build/libs/webapp/webapp-*.jar 2>/dev/null || echo "")
          if [ -z "$WEBAPP_FILE" ]; then
            echo "webapp JAR 파일이 없습니다."
            exit 1
          fi
          mv "$WEBAPP_FILE" ./webapp.jar
          echo "WebApp 빌드 파일 준비 완료: ./webapp.jar"

      # WebServer 빌드 파일 이름 변경
      - name: WebServer 빌드 파일 이름 변경
        run: |
          WEBSERVER_FILE=$(ls ./build/libs/webserver/webserver-*.jar 2>/dev/null || echo "")
          if [ -z "$WEBSERVER_FILE" ]; then
            echo "webserver JAR 파일이 없습니다."
            exit 1
          fi
          mv "$WEBSERVER_FILE" ./webserver.jar
          echo "WebServer 빌드 파일 준비 완료: ./webserver.jar"

      # WebApp 배포 (EC2 #1)
      - name: EC2 WebApp에 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_WEBAPP_HOST }}
          username: ${{ secrets.EC2_WEBAPP_USERNAME }}
          key: ${{ secrets.EC2_WEBAPP_PRIVATE_KEY }}
          source: webapp.jar
          target: /home/ubuntu/hottoke_BE/tobe

      - name: EC2 WebApp 배포 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_WEBAPP_HOST }}
          username: ${{ secrets.EC2_WEBAPP_USERNAME }}
          key: ${{ secrets.EC2_WEBAPP_PRIVATE_KEY }}
          script_stop: true
          script: |
            APP_DIR="/home/ubuntu/hottoke_BE"
            WEBAPP_DIR="$APP_DIR/current/webapp"
            TOBE_DIR="$APP_DIR/tobe"
            JAR_FILE="webapp.jar"

            echo "==== WebApp 배포 시작 ===="

            # current 경로가 파일인지 디렉터리인지 확인
            if [ -e "$APP_DIR/current" ] && [ ! -d "$APP_DIR/current" ]; then
              echo "경로 $APP_DIR/current 는 파일로 존재합니다. 삭제 중..."
              rm -f "$APP_DIR/current"
            fi

            # current 디렉터리 준비
#            if [ ! -d "$APP_DIR/current" ]; then
#              echo "current 디렉터리 생성: $APP_DIR/current"
#              mkdir -p "$APP_DIR/current"
#            else
#              echo "current 디렉터리 이미 존재: $APP_DIR/current"
#            fi

            # 기존 WebApp 디렉터리 삭제 및 새로 생성
            if [ -d "$WEBAPP_DIR" ]; then
              echo "기존 WebApp 디렉터리 삭제: $WEBAPP_DIR"
              rm -rf "$WEBAPP_DIR"
            fi
            mkdir -p "$WEBAPP_DIR"

            # JAR 파일 확인 및 이동
            if [ ! -f "$TOBE_DIR/$JAR_FILE" ]; then
              echo "$JAR_FILE 파일이 없습니다!"
              exit 1
            fi
            mv "$TOBE_DIR/$JAR_FILE" "$WEBAPP_DIR/$JAR_FILE"
            echo "==== WebApp 파일 이동 완료 ===="

            # 기존 프로세스 종료 및 새로운 WebApp 실행
            echo "8080 포트의 기존 프로세스 종료 중..."
            sudo fuser -k -n tcp 8080 || true

            echo "WebApp 실행 시작..."
            nohup java -jar "$WEBAPP_DIR/$JAR_FILE" > "$WEBAPP_DIR/webapp.log" 2>&1 &
            echo "==== WebApp 배포 완료 ===="

      # WebServer 배포 (EC2 #2)
      - name: EC2 WebServer에 파일 전송 (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_WEBSERVER_HOST }}
          username: ${{ secrets.EC2_WEBSERVER_USERNAME }}
          key: ${{ secrets.EC2_WEBSERVER_PRIVATE_KEY }}
          source: webserver.jar
          target: /home/ubuntu/hottoke_BE/tobe

      - name: EC2 WebServer 배포 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_WEBSERVER_HOST }}
          username: ${{ secrets.EC2_WEBSERVER_USERNAME }}
          key: ${{ secrets.EC2_WEBSERVER_PRIVATE_KEY }}
          script_stop: true
          script: |
            APP_DIR="/home/ubuntu/hottoke_BE"
            WEBSERVER_DIR="$APP_DIR/current/webserver"
            TOBE_DIR="$APP_DIR/tobe"
            JAR_FILE="webserver.jar"

            echo "==== WebServer 배포 시작 ===="

            # current 디렉터리 준비
            if [ -e "$APP_DIR/current" ] && [ ! -d "$APP_DIR/current" ]; then
              echo "경로 $APP_DIR/current 는 파일로 존재합니다. 삭제 후 디렉터리 생성."
              rm -f "$APP_DIR/current"
            fi
            mkdir -p "$APP_DIR/current"

            # 기존 WebServer 디렉터리 삭제 및 새로 생성
            if [ -d "$WEBSERVER_DIR" ]; then
              echo "기존 WebServer 디렉터리 삭제: $WEBSERVER_DIR"
              rm -rf "$WEBSERVER_DIR"
            fi
            mkdir -p "$WEBSERVER_DIR"

            # JAR 파일 확인 및 이동
            if [ ! -f "$TOBE_DIR/$JAR_FILE" ]; then
              echo "$JAR_FILE 파일이 없습니다!"
              exit 1
            fi
            mv "$TOBE_DIR/$JAR_FILE" "$WEBSERVER_DIR/$JAR_FILE"
            echo "==== WebServer 파일 이동 완료 ===="

            # 기존 프로세스 종료 및 새로운 WebServer 실행
            echo "8081 포트의 기존 프로세스 종료 중..."
            sudo fuser -k -n tcp 8081 || true

            echo "WebServer 실행 시작..."
            nohup java -jar "$WEBSERVER_DIR/$JAR_FILE" > "$WEBSERVER_DIR/webserver.log" 2>&1 &
            echo "==== WebServer 배포 완료 ===="
